In [3]:
import numpy as np

npa = np.array([1,2,3,4])

npa


array([1, 2, 3, 4])

In [6]:
np.full(10, 40)

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

In [8]:
np.random.randint(180, size=(6,40))

array([[ 33,  49, 172, 135, 124, 114,  49, 166,  33,  65,  11,  16,  95,
        144, 162, 168, 118,   4,  66, 175, 153,  62,  87,  55, 142,  69,
          2, 108, 162,  91,  19, 144,  26, 151,   6, 171,  92,  95,  13,
        161],
       [146, 164,  43,  78, 109, 106,  39,  53, 124, 147,  98, 170,  52,
         83, 147,  79,  73,  58, 137, 101, 155, 136,  33,  54,  42,  32,
         67,  48, 164,  36,  74, 100,  96,  20,  37, 131,  41, 140,  96,
         70],
       [151, 124, 141,  60,  29,  10,  61, 144, 121, 157, 108,  35, 170,
        123, 164,  51,  56,  73,  99,  90, 167,  36,  64, 102,  39, 151,
         60, 174, 106,  62,  96,  68,  94,  14,  21,  39, 163, 149,  37,
         16],
       [ 29, 152,   5,  27, 150,  93,  63,  95, 159,   8,  78,   3,  25,
         43,  13,  12, 159,  32, 119,  34, 176,  79,   1, 130,  64,  98,
        121, 132, 157,  57, 176,  74, 160, 168, 138,  70,   8, 122, 137,
        147],
       [ 84, 131, 131, 118,  26,  67,  58,  98, 164,  73,   8, 116, 